name: LuaRocks release
on:
  push:
    tags: # Will upload to luarocks.org when a tag is pushed
      - 'v*.*.*'
  pull_request: # Will test a local install without uploading to luarocks.org
  workflow_dispatch: # Allows manual triggering

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: env.LUAROCKS_API_KEY != null
      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v7
        if: env.LUAROCKS_API_KEY != null
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
